name: java update
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: List current java versions
        run: |
          ls -ltr
          java -version

      - uses: actions/checkout@v3
      - name: Update Java versions
        uses: actions/setup-java@v3
        with:
          java-version: "11" 
          distribution: 'temurin' 

      - name: Check new version
        run: |
          ls -ltr
          java -version
