name: complex workflow

on:
  push:
    branches:
      - "feature/devp01"

jobs:
  job1:
    name: Ubuntu job
    runs-on: ubuntu-latest
    steps:
      - run: date

  job2:
    name: Windows job
    runs-on: windows-latest
    steps:
      - run: date

  job3:
    name: macos job
    runs-on: macos-latest
    steps:
      - run: date
      
  job4:
    name: dependent job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - run: echo 'Successful exectuion of 3 prior jobs on diff os'
